### ISSUE TITLE
2_css不能构建

### ISSUE THREAD

**Issue by zlllya** [fe-config/generate-pages-tutorial#1]
css好像不能引入，如果去掉/src/page1/main.js里面的 `import './style.css'` 就可以了

错误：
ERROR in ./src/page1/style.css
Module parse failed: E:\test\webpack\2_css\src\page1\style.css Unexpected token (1:5)
You may need an appropriate loader to handle this file type.
| body {
|       background: #333;
| }
 @ ./src/page1/main.js 1:0-20

**Comment by riskers** [comment]
@zouliang073 

2_css 中是这样引入 css 的： https://github.com/fe-config/generate-pages-tutorial/blob/master/2_css/src/page1/main.js#L1

并不是 import ，import 是 4_es2015 的用法

**Comment by zlllya** [comment]
@riskers 咦，这就奇怪了，我明明就这里下载的，我并没有改，为什么下载的和上面不一样，不过谢谢解答
